import React from "react";
import { UserProfile, Roadmap, RoadmapStep, Resource } from "../types";
import { generateCareerGuidance } from "../services/geminiService";
import { motion } from "motion/react";
import { Play, Clock, Milestone, ArrowUpRight, CheckCircle, Info, Download } from "lucide-react";

interface DashboardProps {
  roadmap: Roadmap;
  profile: UserProfile;
  onGoToCareer: (guidance: any) => void;
}

export default function Dashboard({ roadmap, profile, onGoToCareer }: DashboardProps) {
  const handleCareerRequest = async () => {
    const guidance = await generateCareerGuidance(profile);
    onGoToCareer(guidance);
  };

  const downloadLearningPath = () => {
    const content = `
# AI MENTOR HUB - YOUR SYNTHESIS LEARNING PATH

## ANALYSIS & REASONING
${roadmap.recommendationReason}

${roadmap.steps.map((step, i) => `
### PHASE ${i + 1}: ${step.title}
**Milestone:** ${step.milestone}
**Time Commitment:** ${step.estimateHours} Hours
**Level:** ${step.level}

**Curated Resources:**
${step.resources.map(res => `- [${res.title}](${res.url}) [${res.platform}]: ${res.duration}`).join('\n')}
`).join('\n')}

## OPERATIONAL PLAN (WEEKLY)
${roadmap.weeklySchedule.map(item => `- ${item}`).join('\n')}
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-mentor-learning-path.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      {/* Sidebar: Profile Summary */}
      <aside className="lg:col-span-3 space-y-6">
        <div className="p-6 bg-white rounded-2xl border border-slate-200 shadow-sm space-y-5">
          <div className="flex items-center gap-3">
             <div className="w-8 h-8 bg-indigo-50 text-indigo-600 rounded-lg flex items-center justify-center font-bold text-xs uppercase tracking-tighter italic">P</div>
             <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Current Intelligence</p>
          </div>
          
          <div className="space-y-1">
            <p className="text-[10px] font-bold text-slate-400 uppercase">Strategic Goal</p>
            <p className="text-sm font-bold text-slate-800 uppercase tracking-tight">{profile.careerGoal.replace("_", " ")}</p>
          </div>

          <div className="pt-4 border-t border-slate-100 space-y-1">
            <p className="text-[10px] font-bold text-slate-400 uppercase">Availability</p>
            <p className="text-sm font-bold text-slate-800">{profile.timeAvailability}</p>
          </div>
          
          <div className="pt-4 border-t border-slate-100 italic">
            <p className="text-[10px] font-bold text-slate-400 uppercase not-italic mb-2">Gemini Analysis</p>
            <p className="text-[11px] text-slate-500 leading-relaxed font-serif">"{roadmap.recommendationReason.slice(0, 150)}..."</p>
          </div>
        </div>

        <button
          onClick={handleCareerRequest}
          className="w-full flex items-center justify-between p-4 bg-slate-900 text-white rounded-xl text-[11px] font-bold uppercase tracking-wider hover:bg-slate-800 active:scale-[0.98] transition-all shadow-lg shadow-slate-200"
        >
          View Career Guidance <ArrowUpRight size={14} />
        </button>
      </aside>

      {/* Main Path: Steps */}
      <section className="lg:col-span-9 space-y-8">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
          <div>
            <h2 className="text-3xl font-bold text-slate-800 tracking-tight">Your Synthesis Path</h2>
            <p className="text-slate-500 text-sm mt-1">Generated by AI Mentor Hub Neural Core</p>
          </div>
          <div className="flex gap-2">
             <button 
               onClick={downloadLearningPath}
               className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-600 rounded-lg text-[10px] font-bold uppercase hover:bg-slate-50 transition-all shadow-sm"
             >
               <Download size={14} /> Download Protocol
             </button>
             <div className="flex gap-2 bg-white p-1 rounded-xl border border-slate-200">
                <button className="px-5 py-2 bg-indigo-600 text-white rounded-lg text-[10px] font-bold uppercase">Weekly Mode</button>
             </div>
          </div>
        </header>

        <div className="relative space-y-6">
          <div className="absolute left-[23px] top-6 bottom-6 w-0.5 bg-slate-200"></div>
          {roadmap.steps.map((step, idx) => (
            <div key={idx} className="relative z-10">
              <StepRow step={step} index={idx} />
            </div>
          ))}
        </div>

        <div className="p-6 bg-indigo-50/50 rounded-2xl border border-indigo-100 flex flex-col md:flex-row gap-8">
           <div className="md:w-1/3 space-y-2">
             <div className="flex items-center gap-3">
               <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-white"><Clock size={16} /></div>
               <h4 className="text-lg font-bold text-slate-800">Operational Plan</h4>
             </div>
             <p className="text-slate-500 text-xs">Structured weekly strategy based on your bandwidth allocation.</p>
           </div>
           <div className="md:w-2/3 grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3">
             {roadmap.weeklySchedule.map((item, i) => (
               <div key={i} className="flex gap-3 items-start text-[11px] font-medium text-slate-600 border-l-2 border-indigo-200 pl-3 py-1">
                 {item}
               </div>
             ))}
           </div>
        </div>
      </section>
    </div>
  );
}

function StepRow({ step, index }: { step: RoadmapStep, index: number }) {
  const isActive = index === 0;
  return (
    <div className="flex gap-6 group">
      {/* Icon Column */}
      <div className={`w-12 h-12 rounded-full flex items-center justify-center shrink-0 font-bold text-sm transition-all shadow-md ${
        isActive 
          ? "bg-indigo-600 text-white ring-4 ring-indigo-100" 
          : "bg-white text-slate-400 border-2 border-slate-100"
      }`}>
        {index + 1}
      </div>

      {/* Content Card */}
      <div className={`flex-1 bg-white p-6 rounded-2xl border transition-all ${
        isActive 
          ? "border-indigo-200 shadow-xl shadow-indigo-50/50" 
          : "border-slate-100 hover:border-slate-200 opacity-80 hover:opacity-100"
      }`}>
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-4">
           <div>
              <div className="flex items-center gap-2 mb-1">
                <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full uppercase tracking-widest ${
                  isActive ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-500"
                }`}>
                  Phase {index + 1} // {step.level}
                </span>
              </div>
              <h4 className="text-xl font-bold text-slate-800 tracking-tight leading-tight">{step.title}</h4>
           </div>
           <div className="flex items-center gap-4 text-[11px] font-bold text-slate-400 uppercase">
             <span className="flex items-center gap-1.5"><Clock size={14} className="text-indigo-400" /> {step.estimateHours} Hrs</span>
             <span className="flex items-center gap-1.5"><Milestone size={14} className="text-indigo-400" /> {step.milestone}</span>
           </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-6">
          {step.resources.map((res, i) => (
            <a
              key={i}
              href={res.url}
              target="_blank"
              className="group/item flex items-center justify-between p-3.5 bg-slate-50 rounded-xl border border-slate-100 hover:border-indigo-200 hover:bg-white hover:shadow-md transition-all"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 flex items-center justify-center bg-slate-900 rounded-lg shrink-0">
                  <span className="text-indigo-500 font-black text-[10px] leading-none tracking-tighter">AI</span>
                </div>
                <div>
                  <h5 className="text-[11px] font-bold text-slate-700 leading-tight line-clamp-1">{res.title}</h5>
                  <p className="text-[9px] text-slate-400 font-semibold uppercase">{res.platform} • {res.duration}</p>
                </div>
              </div>
              <div className="w-7 h-7 flex items-center justify-center rounded-full bg-indigo-50 text-indigo-600 opacity-0 group-hover/item:opacity-100 transition-all origin-left scale-50 group-hover/item:scale-100">
                <Play size={12} fill="currentColor" />
              </div>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
